// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
// Calls marked [revert-tolerant] are wrapped in try/catch: ESBMC could
// not confirm the call's outcome, so an undetected revert (e.g.
// require(cond, CustomError)) does not FAIL the assertion-free replay.
// The wrap does NOT assert a revert; a non-reverting call runs normally.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {FeeVault} from "../src/flat.sol";

contract FeeVaultCovTest_0_FeeVault_withdraw_put119p1 is Test {
  FeeVault c0;
  function setUp() public {
    vm.startPrank(address(uint160(1)), address(uint160(1)));
    c0 = new FeeVault();
    // [strict no-fake-state 2026-09-08] the former `vm.deal(address(c0), 1 << 128)`
    // balance pin is REMOVED: the contract's balance now comes solely from the real
    // deposit() transaction below, so the ledger can never exceed actual holdings.
    vm.stopPrank();
  }
  // claim: sol:@C@FeeVault@F@deposit#56:path:1
  // witness-fingerprint-sha256: 380604d4d2f729fe26191e24bea4c500a52155e41232f10cfdca2749d5130f8a
  // claim: sol:@C@FeeVault@F@setDiscount#81:path:7
  // witness-fingerprint-sha256: 3b8e1bf266233a6b096edae58abdba028b2ca1d77f688da4c607c223492e8557
  // claim: sol:@C@FeeVault@F@setDiscount#81:path:6
  // witness-fingerprint-sha256: 81a3f91fe4e42f838a0f125f68a3691ed5e9d0655fe28c4b06c64e9229c33e0b
  // claim: sol:@C@FeeVault@F@setDiscount#81:path:2
  // witness-fingerprint-sha256: 6fa68b71c6ad2a5fb9c2cba5e46a52f8cae79da5f86629c6ac22d5eac5394e4a
  // claim: sol:@C@FeeVault@F@withdraw#193:path:6
  // witness-fingerprint-sha256: 72f8ad7d296131d5e4841c5c57601910b331391a28c5da747b58bde3141b1194
  // claim: sol:@C@FeeVault@F@withdraw#193:path:2
  // witness-fingerprint-sha256: ebefe36189b3f5ab8f29ff8996ed3eb66c00075fe8d18445accb02520ff71e1e
  // claim: sol:@C@FeeVault@F@withdraw#193:path:127, sol:@C@FeeVault@F@withdraw#193:path:62
  // witness-fingerprint-sha256: 62e8f46db1d51e15f04621290875d23e2a96e77d5a5a27497df262708a07a24f
  // claim: sol:@C@FeeVault@F@withdraw#193:path:119, sol:@C@FeeVault@F@withdraw#193:path:58
  // witness-fingerprint-sha256: ff008fab471f426e35d7c01bd8731e94a22dc9fef87bc188dd2e2b6804616167

  // ===================== PUT (stage 4) =====================
  // claim: sol:@C@FeeVault@F@withdraw#193:path:119   depth=6
  // CELL UNNAMED -- scope=deposit,setDiscount,withdraw --solidity-max-tx=3 is neither of the two command lines INVOCATION_DECISIONS.md settles, so this run belongs to no table. Say what it is for before quoting it anywhere
  // CERTIFIED REGION (stage 2), certified by an independent
  // `assume(box); assert(tr == pi)` query, not by the subtraction:
  //   amount in [1, 1]
  //   block.number in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935]
  //   block.timestamp in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935]
  //   msg.sender in [0, 4294967295]
  //   state.deposits$19[msg.sender] in [1, 115792089237316195423570985008687907853269984665640564039457584007913129639935]
  //   state.discountBps$23[msg.sender] in [1, 250]
  //   state.feeReceiver in [0, 1461501637330902918203684832716283019655932542975]
  //   PIN block.basefee == 0
  //   PIN block.blobbasefee == 0
  //   PIN block.chainid == 0
  //   PIN block.coinbase == 0
  //   PIN block.difficulty == 0
  //   PIN block.prevrandao == 0
  //   PIN msg.value == 0
  //   PIN state.feeBps == 250   [NOT ESTABLISHED -- see the dropped-bound line]
  //   PIN state.maxFee == 100000000000000000   [NOT ESTABLISHED -- see the dropped-bound line]
  //   PIN tx.gasprice == 0
  // WIDTH PROVENANCE (stage-2 switches for this ROW, not per coordinate):
  //   claim_budget = 0
  //   cut_policy = spec
  //   esbmc_args = ['--extcall-nondet', '--unwindsetname', '_ESBMC_alloc_nested_2d:0:16,nondet_string:0:33']
  //   geometric_bracket = False
  //   level0 = True
  //   level0_perturb = True
  //   level0_points = {'6': '(none)', '115': '(none)', '119': '(none)', '123': '(none)', '127': '(none)'}
  //   max_holes = 3
  //   max_region_pieces = 4
  //   max_tx = 3
  //   probe_ladder = True
  //   probe_ladder_budget = 8
  //   probes = 8
  //   refine_rounds = 1
  //   region_refinement_used = True
  //   scope = deposit,setDiscount,withdraw
  //   shrink_rounds = 4
  //   sibling_subtraction = True
  //   skip_bracket = True
  // Width sources that ran: subtraction of the sibling paths
  // Arguments the region does NOT bound keep the counterexample's own
  // literal: the region is a statement about THAT slice, and generalising
  // over them would be a claim the certification never made.
  // FUZZ COORDINATES: msg.sender, block.timestamp, block.number, amount
  // ORACLE: 109 assertion(s) from the surviving (HOLDS) rungs of
  // --path-cov-assert -- 35 over POST-STATE, read through vm.load at
  // the slot solc reports, and 74 over the unit's OWN RETURN
  // VALUE, bound from the call below. A return rung is emitted only when the
  // ladder's `retlive` witness was REFUTED, i.e. only when this path was
  // shown to reach a return at all.
  //   rung IMPLIED (not lost, not asserted twice): feeReceiver: post >= pre (entailed by a stronger rung that also HOLDS on feeReceiver, so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): feeReceiver: post <= pre (entailed by a stronger rung that also HOLDS on feeReceiver, so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): deposits$19[msg.sender]: post != pre (entailed by a stronger rung that also HOLDS on deposits$19[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): deposits$19[msg.sender]: post <= pre (entailed by a stronger rung that also HOLDS on deposits$19[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): discountBps$23[msg.sender]: post >= pre (entailed by a stronger rung that also HOLDS on discountBps$23[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): discountBps$23[msg.sender]: post <= pre (entailed by a stronger rung that also HOLDS on discountBps$23[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): deposits[msg.sender]: post != pre (entailed by a stronger rung that also HOLDS on deposits[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): deposits[msg.sender]: post <= pre (entailed by a stronger rung that also HOLDS on deposits[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): discountBps[msg.sender]: post >= pre (entailed by a stronger rung that also HOLDS on discountBps[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): discountBps[msg.sender]: post <= pre (entailed by a stronger rung that also HOLDS on discountBps[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): return: return != 0 (entailed by a stronger rung that also HOLDS on return, so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): feeReceiver: post == (pre * amount) (entailed by a stronger rung that also HOLDS on feeReceiver, so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): discountBps$23[msg.sender]: post == (pre * amount) (entailed by a stronger rung that also HOLDS on discountBps$23[msg.sender], so asserting it detects nothing the stronger one misses)
  //   rung IMPLIED (not lost, not asserted twice): return: return in [1, 1] (entailed by a stronger rung that also HOLDS on return, so asserting it detects nothing the stronger one misses)
  //   path guard ESTABLISHED: `!((discountBps[msg.sender]) > 0)` -> `vm.assume(_pre_discountBps_msg_sender > 0);`
  //   path guard DROPPED: '!(amount > 0 && amount <= d)' (`d` is assigned inside the unit before this source decision may execute, so it is not the calldata coordinate)
  //   path guard DROPPED: 'fee > maxFee' (`fee` is assigned inside the unit before this source decision may execute, so it is not the calldata coordinate)
  //   path guard DROPPED: '!ok1' (`ok1` is not nameable in this PUT)
  //   path guard DROPPED: '!ok2' (`ok2` is not nameable in this PUT)
  //   entry-state bound DROPPED: state.feeBps (no storage slot: solc's layout does not list it, so it is a constant/immutable and no test can set it)
  //   entry-state bound DROPPED: state.feeReceiver in [0, 1461501637330902918203684832716283019655932542975] (width > 1, DROPPED: the entry state is not havoc'd, so this bound constrained nothing in the query -- the rungs were proved about the constructor's own value. Establishing a fuzz-chosen value here would test entry states the proof never covered, which is how this PUT came back RED on the unmodified contract. Both endpoints are the type's own limits, so there is not even an in-region check to make: the bound says nothing at all)
  //   entry-state bound DROPPED: state.maxFee (no storage slot: solc's layout does not list it, so it is a constant/immutable and no test can set it)
  //   environment ESTABLISHED: msg.sender in [0, 4294967295]  \ {0} is ESTABLISHED and FUZZED: the governing vm.prank now takes the bound() fuzz parameter `p_msg_sender`, so this PUT ranges over the certified sender interval rather than over one point of it, and the 1 punched value(s) are excluded by vm.assume; 0 is excluded because Foundry cannot prank address(0), and the remaining executable subregion is a subset of the certified region (replacing `vm.prank(address(uint160(0)));`)
  //   environment ESTABLISHED: block.timestamp in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935] is ESTABLISHED and FUZZED: vm.warp now takes the bound() fuzz parameter `p_block_timestamp`
  //   environment ESTABLISHED: block.number in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935] is ESTABLISHED and FUZZED: vm.roll now takes the bound() fuzz parameter `p_block_number`
  //   environment ESTABLISHED: block.chainid == 0 is ESTABLISHED with `vm.chainId(0)` before the target call
  //   environment ESTABLISHED: block.basefee == 0 is ESTABLISHED with `vm.fee(0)` before the target call
  //   environment ESTABLISHED: block.blobbasefee == 0 is ESTABLISHED with `vm.blobBaseFee(0)` before the target call
  //   environment ESTABLISHED: block.difficulty is established by the matching block.prevrandao cheatcode
  //   environment ESTABLISHED: block.prevrandao == 0 is ESTABLISHED with `vm.prevrandao(uint256(0))` before the target call
  //   environment ESTABLISHED: tx.gasprice == 0 is ESTABLISHED with `vm.txGasPrice(0)` before the target call
  //   environment ESTABLISHED: block.coinbase == 0 is ESTABLISHED with `vm.coinbase(address(uint160(0)))` before the target call
  function test_put_FeeVault_withdraw_path119p1(address p_msg_sender, uint256 p_block_timestamp, uint256 p_block_number, uint256 amount, uint256 s_deposits_19_msg_sender, uint16 s_discountBps_23_msg_sender) public {
    p_msg_sender = address(uint160(bound(uint256(uint160(p_msg_sender)), 0, 4294967295)));
    vm.assume(uint256(uint160(p_msg_sender)) != 0);
    p_block_timestamp = bound(p_block_timestamp, 0, 115792089237316195423570985008687907853269984665640564039457584007913129639935);
    p_block_number = bound(p_block_number, 0, 115792089237316195423570985008687907853269984665640564039457584007913129639935);
    amount = bound(amount, 1, 1);
    s_deposits_19_msg_sender = bound(s_deposits_19_msg_sender, 1, type(uint256).max);
    s_discountBps_23_msg_sender = uint16(bound(uint256(s_discountBps_23_msg_sender), 1, 250));
    // entry state ESTABLISHED BY REAL TRANSACTIONS ([strict no-fake-state 2026-09-08];
    // the former vm.store writes are REMOVED):
    //   deposits[p_msg_sender] := s_deposits_19_msg_sender via an actual
    //   deposit{value: s}() from p_msg_sender, so ledger == contract balance by
    //   construction (the on-chain-impossible "ledger exceeds holdings" state can
    //   no longer be constructed);
    //   discountBps[p_msg_sender] := s_discountBps_23_msg_sender via the owner's
    //   setDiscount (owner is the deployer, address(1), pranked in setUp).
    // The fuzzed deposit range is the FULL certified interval [1, 2^256-1]: the
    // real deposit{value: s}() transaction establishes any word-sized ledger value.
    vm.deal(p_msg_sender, s_deposits_19_msg_sender);
    vm.prank(p_msg_sender);
    c0.deposit{value: s_deposits_19_msg_sender}();
    vm.prank(address(uint160(1)));
    c0.setDiscount(p_msg_sender, s_discountBps_23_msg_sender);
    assertGe(uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(2))))), uint256(1), "the entry state is OUTSIDE the certified region: state.deposits$19[msg.sender] was assumed in [1, 115792089237316195423570985008687907853269984665640564039457584007913129639935] when the path was certified, so a value outside it means the assumption was vacuous and the rungs below were proved about no execution this test can reach");
    assertGe((uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535), uint256(1), "the entry state is OUTSIDE the certified region: state.discountBps$23[msg.sender] was assumed in [1, 250] when the path was certified, so a value outside it means the assumption was vacuous and the rungs below were proved about no execution this test can reach");
    assertLe((uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535), uint256(250), "the entry state is OUTSIDE the certified region: state.discountBps$23[msg.sender] was assumed in [1, 250] when the path was certified, so a value outside it means the assumption was vacuous and the rungs below were proved about no execution this test can reach");
    // pre-state for the oracle, at this path's own entry
    uint256 _pre_feeReceiver = (uint256(vm.load(address(c0), bytes32(uint256(1)))) & 1461501637330902918203684832716283019655932542975);
    uint256 _pre_deposits_19_msg_sender = uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(2)))));
    uint256 _pre_discountBps_23_msg_sender = (uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535);
    uint256 _pre_deposits_msg_sender = uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(2)))));
    uint256 _pre_discountBps_msg_sender = (uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535);
    // complete-path guard recovered from the emit report
    vm.assume(_pre_discountBps_msg_sender > 0);
    vm.warp(p_block_timestamp);
    vm.roll(p_block_number);
    vm.chainId(0);
    vm.fee(0);
    vm.blobBaseFee(0);
    vm.prevrandao(uint256(0));
    vm.txGasPrice(0);
    vm.coinbase(address(uint160(0)));
    // certified extcall success pin on msg.sender: the lifted caller must accept a bare call
    assumeNotPrecompile(p_msg_sender);
    vm.assume(p_msg_sender.code.length == 0);
    vm.prank(p_msg_sender);
    // [asserted] path exits normally; a revert fails the test
    uint256 _put_ret = c0.withdraw(amount);
    // VERIPUT_ORACLE_REFINEMENT_BEGIN
    uint256 _post_feeReceiver = (uint256(vm.load(address(c0), bytes32(uint256(1)))) & 1461501637330902918203684832716283019655932542975);
    uint256 _post_deposits_19_msg_sender = uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(2)))));
    uint256 _post_discountBps_23_msg_sender = (uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535);
    uint256 _post_deposits_msg_sender = uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(2)))));
    uint256 _post_discountBps_msg_sender = (uint256(vm.load(address(c0), keccak256(abi.encode(p_msg_sender, uint256(3))))) & 65535);
    assertEq(_post_feeReceiver, _pre_feeReceiver, "feeReceiver: post == pre");
    assertLt(_post_deposits_19_msg_sender, _pre_deposits_19_msg_sender, "deposits$19[msg.sender]: post < pre");
    assertEq(_post_discountBps_23_msg_sender, _pre_discountBps_23_msg_sender, "discountBps$23[msg.sender]: post == pre");
    // [dedup R2] removed: assertLt(_post_deposits_msg_sender, _pre_deposits_msg_sender, "deposits[msg.sender]: post < pre");
    // [dedup R2] removed: assertEq(_post_discountBps_msg_sender, _pre_discountBps_msg_sender, "discountBps[msg.sender]: post == pre");
    unchecked { assertEq(_post_deposits_msg_sender, (uint256(_pre_deposits_msg_sender) - uint256(amount)), "deposits[msg.sender]: post == (state.deposits[msg.sender] - amount)"); }
    // [dedup R2] removed: assertEq(_post_feeReceiver, _pre_feeReceiver, "feeReceiver: post == state.feeReceiver");
    // [dedup R3] removed: assertGe(_post_feeReceiver, 0, "feeReceiver: post in [0, pre]");
    // [dedup R4] removed: assertLe(_post_feeReceiver, _pre_feeReceiver, "feeReceiver: post in [0, pre]");
    // [dedup R2] removed: unchecked { assertEq(_post_deposits_19_msg_sender, (uint256(_pre_deposits_19_msg_sender) - uint256(amount)), "deposits$19[msg.sender]: post == (pre - amount)"); }
    // [dedup R3] removed: assertGe(_post_deposits_19_msg_sender, 0, "deposits$19[msg.sender]: post in [0, pre]");
    assertLe(_post_deposits_19_msg_sender, _pre_deposits_19_msg_sender, "deposits$19[msg.sender]: post in [0, pre]");
    // [dedup R3] removed: assertGe(_post_deposits_19_msg_sender, 0, "deposits$19[msg.sender]: post in [0, (pre - amount)]");
    // [dedup R4] removed: unchecked { assertLe(_post_deposits_19_msg_sender, (uint256(_pre_deposits_19_msg_sender) - uint256(amount)), "deposits$19[msg.sender]: post in [0, (pre - amount)]"); }
    assertGe(_pre_deposits_19_msg_sender, _post_deposits_19_msg_sender, "deposits$19[msg.sender]: pre - post in [amount, amount] with pre >= post");
    unchecked { assertGe(_pre_deposits_19_msg_sender - _post_deposits_19_msg_sender, amount, "deposits$19[msg.sender]: pre - post in [amount, amount] with pre >= post"); }
    unchecked { assertLe(_pre_deposits_19_msg_sender - _post_deposits_19_msg_sender, amount, "deposits$19[msg.sender]: pre - post in [amount, amount] with pre >= post"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, pre]");
    // [dedup R4] removed: assertLe(_post_discountBps_23_msg_sender, _pre_discountBps_23_msg_sender, "discountBps$23[msg.sender]: post in [0, pre]");
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, state.feeBps]");
    assertLe(_post_discountBps_23_msg_sender, 250, "discountBps$23[msg.sender]: post in [0, state.feeBps]");
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, 10000]");
    assertLe(_post_discountBps_23_msg_sender, 10000, "discountBps$23[msg.sender]: post in [0, 10000]");
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre + pre)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) + uint256(_pre_discountBps_23_msg_sender)), "discountBps$23[msg.sender]: post in [0, (pre + pre)]"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre * pre)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) * uint256(_pre_discountBps_23_msg_sender)), "discountBps$23[msg.sender]: post in [0, (pre * pre)]"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre + amount)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) + uint256(amount)), "discountBps$23[msg.sender]: post in [0, (pre + amount)]"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre + state.feeBps)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) + uint256(250)), "discountBps$23[msg.sender]: post in [0, (pre + state.feeBps)]"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre * state.feeBps)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) * uint256(250)), "discountBps$23[msg.sender]: post in [0, (pre * state.feeBps)]"); }
    // [dedup R3] removed: assertGe(_post_discountBps_23_msg_sender, 0, "discountBps$23[msg.sender]: post in [0, (pre + 10000)]");
    unchecked { assertLe(_post_discountBps_23_msg_sender, (uint256(_pre_discountBps_23_msg_sender) + uint256(10000)), "discountBps$23[msg.sender]: post in [0, (pre + 10000)]"); }
    // [dedup R5] removed: assertTrue(uint256(_put_ret) != 0, "return: return != 0");
    assertEq(uint256(_put_ret), amount, "return: return == amount");
    // [dedup R2] removed: assertEq(uint256(_put_ret), 1, "return: return == 1");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) * uint256(amount)), "return: return == (amount * amount)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) + uint256(0)), "return: return == (amount + msg.value)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) - uint256(0)), "return: return == (amount - msg.value)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) + uint256(0)), "return: return == (amount + 0)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) - uint256(0)), "return: return == (amount - 0)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(amount) * uint256(1)), "return: return == (amount * 1)");
    // [dedup R2] removed: assertEq(uint256(_put_ret), (uint256(0) + uint256(amount)), "return: return == (msg.value + amount)");
    // [dedup R4] removed: assertGe(uint256(_put_ret), amount, "return: return in [amount, amount]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), amount, "return: return in [amount, amount]");
    // [dedup R4] removed: assertGe(uint256(_put_ret), 1, "return: return in [1, 1]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), 1, "return: return in [1, 1]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, amount]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), amount, "return: return in [0, amount]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, state.feeBps]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 250, "return: return in [0, state.feeBps]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, state.maxFee]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 100000000000000000, "return: return in [0, state.maxFee]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 250]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 250, "return: return in [0, 250]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 10000]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 10000, "return: return in [0, 10000]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 1]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), 1, "return: return in [0, 1]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 115792089237316195423570985008687907853269984665640564039457584007913129639935, "return: return in [0, 115792089237316195423570985008687907853269984665640564039457584007913129639935]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 4294967295]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 4294967295, "return: return in [0, 4294967295]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 1461501637330902918203684832716283019655932542975]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 1461501637330902918203684832716283019655932542975, "return: return in [0, 1461501637330902918203684832716283019655932542975]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, 100000000000000000]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), 100000000000000000, "return: return in [0, 100000000000000000]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + amount)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(amount)), "return: return in [0, (amount + amount)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * amount)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(amount)), "return: return in [0, (amount * amount)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + msg.value)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(0)), "return: return in [0, (amount + msg.value)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount - msg.value)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) - uint256(0)), "return: return in [0, (amount - msg.value)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + state.feeBps)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(250)), "return: return in [0, (amount + state.feeBps)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * state.feeBps)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(250)), "return: return in [0, (amount * state.feeBps)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + state.maxFee)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(100000000000000000)), "return: return in [0, (amount + state.maxFee)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * state.maxFee)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(100000000000000000)), "return: return in [0, (amount * state.maxFee)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 0)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(0)), "return: return in [0, (amount + 0)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount - 0)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) - uint256(0)), "return: return in [0, (amount - 0)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 250)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(250)), "return: return in [0, (amount + 250)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * 250)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(250)), "return: return in [0, (amount * 250)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 10000)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(10000)), "return: return in [0, (amount + 10000)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * 10000)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(10000)), "return: return in [0, (amount * 10000)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 1)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(1)), "return: return in [0, (amount + 1)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * 1)]");
    // [dedup R4] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(1)), "return: return in [0, (amount * 1)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * 115792089237316195423570985008687907853269984665640564039457584007913129639935)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(115792089237316195423570985008687907853269984665640564039457584007913129639935)), "return: return in [0, (amount * 115792089237316195423570985008687907853269984665640564039457584007913129639935)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 4294967295)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(4294967295)), "return: return in [0, (amount + 4294967295)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount * 4294967295)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) * uint256(4294967295)), "return: return in [0, (amount * 4294967295)]");
    // [dedup R3] removed: assertGe(uint256(_put_ret), 0, "return: return in [0, (amount + 1461501637330902918203684832716283019655932542975)]");
    // [dedup R5] removed: assertLe(uint256(_put_ret), (uint256(amount) + uint256(1461501637330902918203684832716283019655932542975)), "return: return in [0, (amount + 1461501637330902918203684832716283019655932542975)]");
    // VERIPUT_ORACLE_REFINEMENT_END
  }
}

contract FeeVaultCovTest_1 is Test {
  FeeVault c0;
  function setUp() public {
    vm.startPrank(address(uint160(4294967295)), address(uint160(4294967295)));
    c0 = new FeeVault();
    vm.stopPrank();
  }
  // claim: sol:@C@FeeVault@F@withdraw#193:path:60
  // witness-fingerprint-sha256: fd21ba3be0c6a992cbe55bff1492c61739b18f0c39e1db6b69f554fcb2ae2ce6
  // claim: sol:@C@FeeVault@F@withdraw#193:path:123
  // witness-fingerprint-sha256: 3bd762c73866539a52b6adcd223a7eaef8f028b6ffda73dd71111a2da9a8eb61
}

contract FeeVaultCovTest_2 is Test {
  FeeVault c0;
  function setUp() public {
    vm.startPrank(address(uint160(4290772991)), address(uint160(4290772991)));
    c0 = new FeeVault();
    vm.stopPrank();
  }
  // claim: sol:@C@FeeVault@F@withdraw#193:path:56
  // witness-fingerprint-sha256: 316b48cd8f559f4845271469b50ce9eaace1193dc362d1adbdc391dbaca873fa
}

contract FeeVaultCovTest_3 is Test {
  FeeVault c0;
  function setUp() public {
    vm.startPrank(address(uint160(2147483648)), address(uint160(2147483648)));
    c0 = new FeeVault();
    vm.stopPrank();
  }
  // claim: sol:@C@FeeVault@F@withdraw#193:path:115
  // witness-fingerprint-sha256: 90dd9e82546ae4416c187a1b42efcf01817f19ed5d12d6e00320585696df67ba
}
